### ISSUE TITLE
Game Freeze after "spawn_truck"

### ISSUE THREAD

**Issue by RobiZona** [Silonugget/redm-truck#1]
Hi, i tried to spawn truck but game freeze

this is server.cfg

    ensure httpmanager
    ensure pmms
    ensure redm-truck
    
usually this is a render model problem

**Comment by RobiZona** [comment]
![immagine](https://github.com/Silonugget/redm-truck/assets/72941167/d1fb2ac0-a0be-48f0-adf3-9efd91a1275d)

**Comment by Silonugget** [comment]
To resolve this please go in game to Advanced Graphics settings and change it back to Vulcan instead of DX12. You are correct, the truck can only render under Vulkan.

**Comment by RobiZona** [comment]
Thanks!!
